"""migration

Revision ID: 1465730ae9fc
Revises: 
Create Date: 2024-10-18 16:23:48.534476

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1465730ae9fc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('invite_token')
    with op.batch_alter_table('cards', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.String(length=250), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cards', schema=None) as batch_op:
        batch_op.drop_column('description')

    op.create_table('invite_token',
    sa.Column('token', sa.VARCHAR(length=1000), nullable=False),
    sa.Column('adminID', sa.INTEGER(), nullable=False),
    sa.Column('email', sa.VARCHAR(length=255), nullable=False),
    sa.ForeignKeyConstraint(['adminID'], ['workspaces.admin_id'], ),
    sa.PrimaryKeyConstraint('token')
    )
    # ### end Alembic commands ###
